# Build latest code with Gatsby and deploy to dbowland.com
name: Deploy dbowland.com

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Generate static site and deploy to dbowland.com
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Set git name and email
        run: |
          git config --local user.email "dbowland1+bot@gmail.com"
          git config --local user.name "github-actions[bot]"
      - name: Install packages and run tests
        run: npm ci && npm run test src/
        env:
          NODE_ENV: test
      - name: Build Gatsby site
        run: npm run build:prod
        env:
          NODE_ENV: production
      - name: Bump the minor version
        run: npm version minor
      - name: Deploy the build site to dbowland.com
        run: node deploy/index.js
        env:
          DBOWLAND_SSH_USER: ${{ secrets.DBOWLAND_SSH_USER }}
          DBOWLAND_SSH_PASS: ${{ secrets.DBOWLAND_SSH_PASS }}
      - name: Remove Husky Git hooks
        run: rm -rf .husky
      - name: Push tag created by version bump
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
